name: CI for C#

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Defina a versão do .NET conforme necessário

      - name: Restaurar Dependências
        run: dotnet restore

      - name: Executar Testes
        run: dotnet test
